$torch.gather(input, dim, index, out=None):$ 沿给定``dim``, 将输入索引张量``index``指定位置的值进行聚合.

``gather()``根据索引返回该项元素, 根据``dim``判断根据``行/列``进行查找，返回``tendor``的``size``与``index``的``size``一致.

``index``必须为``LongTensor``类型

In [13]:
import torch

In [14]:
a = torch.Tensor([[1, 2], [3, 4]])
print(a)

tensor([[1., 2.],
        [3., 4.]])


In [15]:
index = torch.LongTensor([[0, 0], [1, 0]])
b = torch.gather(a,0, index)
print(b)

tensor([[1., 2.],
        [3., 2.]])


In [16]:
c = torch.gather(a,1, index)
print(c)

tensor([[1., 1.],
        [4., 3.]])


**【详细分析】**  
1.输出形状与``index``的形状一致，``(2, 2)``即两行两列;   
初始数据：  
[ [1, 2],  
[3 ,4] ]  
各元素的位置信息为：  
[ [(0,0), (0,1)],  
[(1,0) ,(1,1)] ]  
``index``形状：  
[ [0, 0],  
[1 ,0] ]  
由上可知, 初始形状中每个元素位置有两个参数(第几行第几列), 但``index``只提供了一个参数;  
2.``dim``: 表示了将``index``替换掉初始数据位置信息中的那个参数, ``0``代表替换行参数，``1``代表替换列参数;  
当dim=0时，初始数据位置信息中行参数被替换为``index``的值：  
[ [(0,0), (0,1)],  
[(1,0) ,(0,1)] ]  
填入对应位置元素得到：  
[ [ 1, 2],  
[3 ,2] ]  
当dim=0时，初始数据位置信息中列参数被替换为``index``的值：  
[ [(0,0), (0,0)],  
[(1,1) ,(1,0)] ]  
填入对应位置元素得到：  
[ [ 1, 1],  
[4 ,3] ]

In [17]:
a = torch.arange(0,16).view(4,4)
print(a)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])


In [18]:
# 选取对角线的元素
index = torch.LongTensor([[0,1,2,3]])
b = a.gather(0,index)
print(b)

tensor([[ 0,  5, 10, 15]])


In [19]:
# 选取反对角线上的元素，注意与上面的不同
index2 = torch.LongTensor([[3,2,1,0]])
c = a.gather(0,index2)
print(c)

tensor([[12,  9,  6,  3]])


In [21]:
# 选取对角线的元素
index3 = torch.LongTensor([[0,1,2,3]]).t()  # torch.t()是一个类似于求矩阵的转置的函数，要求输入的tensor结构维度<=2D
d = a.gather(1,index3)
print(d)

tensor([[ 0],
        [ 5],
        [10],
        [15]])


In [23]:
# 选取反对角线上的元素
index4 = torch.LongTensor([[3,2,1,0]]).t()
e = a.gather(1,index4)
print(e)

tensor([[ 3],
        [ 6],
        [ 9],
        [12]])
