#### 1. torch.squeeze()函数：去掉维数为 1 的维度，对不为 1 的维度无影响;

In [21]:
import torch

In [22]:
a = torch.tensor([[[1, 2], [3, 4]]])
print(a.shape)
print(a)

torch.Size([1, 2, 2])
tensor([[[1, 2],
         [3, 4]]])


In [23]:
b = torch.squeeze(a)
print(b.shape)
print(b)

torch.Size([2, 2])
tensor([[1, 2],
        [3, 4]])


In [24]:
b = a.squeeze()
print(b.shape)
print(b)

torch.Size([2, 2])
tensor([[1, 2],
        [3, 4]])


In [25]:
# 去掉指定维度
b = a.squeeze(0)
print(b.shape)
print(b)

torch.Size([2, 2])
tensor([[1, 2],
        [3, 4]])


In [26]:
# 去掉指定维度
b = a.squeeze(-3)
print(b.shape)
print(b)

torch.Size([2, 2])
tensor([[1, 2],
        [3, 4]])


In [27]:
# 对非维数不为 1 的维度无影响
b = a.squeeze(1)
print(b.shape)
print(b)

torch.Size([1, 2, 2])
tensor([[[1, 2],
         [3, 4]]])


#### 2. torch.unsqueeze()函数：在指定位置增加一个维度;

In [28]:
c = a.unsqueeze(2)
print(c.shape)
print(c)

torch.Size([1, 2, 1, 2])
tensor([[[[1, 2]],

         [[3, 4]]]])


In [29]:
c = torch.unsqueeze(a, 3)
print(c.shape)
print(c)

torch.Size([1, 2, 2, 1])
tensor([[[[1],
          [2]],

         [[3],
          [4]]]])


#### 3. np.expand_dims()函数：在指定位置增加一个维度;