In [49]:
import numpy as np
import random

#### 1. random.random(): 生成 ``[0, 1)`` 之间随机浮点数；  

In [50]:
a = np.random.random([2, 3])  # 传入 [2, 3]
print(a)

[[0.84441349 0.87747192 0.94787905]
 [0.07294418 0.13569308 0.42234696]]


#### 2. random.rand(): 生成 ``[0, 1）`` 之间随机浮点数；

In [51]:
b = np.random.rand(2, 3)  # 输入 2 和 3
print(b)

[[0.83193209 0.72470214 0.38554084]
 [0.48932981 0.5063402  0.13112984]]


#### 3. random.randn(): 返回服从标准正态分布(0为均值，1为标准差)的随机样本；

In [52]:
a = np.random.randn(3)  
print(a)

[-1.66106785  0.70856553 -0.82095113]


In [53]:
a = np.random.randn(2, 3)  
print(a)

[[-0.04985471  1.81975319 -0.02305089]
 [-1.86269452 -1.64777523  1.13046726]]


#### 4. random.standard_normal(): 返回服从标准正态分布的随机样本；

In [54]:
a = np.random.standard_normal([2, 3])
print(a)

[[-0.42201014  0.03731881  0.58042077]
 [-1.34886775 -0.21847856 -0.11361474]]


#### 5. random.randint(): 返回整型随机样本；

In [55]:
a = np.random.randint(1, 8)
print(a)

5


#### 6. random.choice(): 从序列中随机获取元素；

In [56]:
a = np.random.choice([1, 2, 3, 5, 9])
print(a)

5


#### 7. random.shuffle(): 洗牌 (改变排列顺序)；

In [57]:
a = [1, 2, 3, 4]
b = np.random.shuffle(a)
print(a)
print(b)

[2, 4, 1, 3]
None


#### 8. random.permutation(): 洗牌 (不改变排列顺序)；

In [58]:
a = [1, 2, 3, 4]
b = np.random.permutation(a)
print(a)
print(b)

[1, 2, 3, 4]
[1 2 3 4]


#### 9. random.sample(): 截取列表指定长度的随机数, 不改变列表本身排序；

In [62]:
a = [1, 2, 3, 4]
b = random.sample(a, 3)  # 注意：没有使用 np, random.sample()
print(a)
print(b)

[1, 2, 3, 4]
[4, 1, 3]


In [63]:
a = np.random.sample(3)  # 注意：使用 np.random.sample()
print(a)

[0.7376136  0.80933824 0.4991936 ]


与 range 结合，在指定范围内获取一定长度的数据

In [64]:
a = random.sample(range(0, 9), 5)
print(a)

[7, 4, 6, 5, 3]
